---
- hosts: all
  vars:
  handlers:
  tasks:
    - include: start.yml
      tags:
        - start

    - include: stop.yml
      tags:
        - stop

    - include: config-changed.yml
      tags:
        - config-changed

    - include: upgrade-charm.yml
      tags:
        - upgrade-charm

    - include: whisper-relation.yml
      tags:
        - whisper_in-relation-changed
